### ISSUE TITLE
Modification 

### ISSUE THREAD

**Issue by iTzAndrew33212** [TrFolwe/WorldGuardian#1]
hi there,
brilliant so far, would it be possible to update this so that each of the areas have a priority between like 1-10
for a prison server so spawn is noneditable but mines are

Much appreciated thanks
Andrew.

**Comment by TrFolwe** [comment]
@iTzAndrew33212  Hi, I wish you a good morning and holidays, i would appreciate it if you could explain the first priority in the fields and the last priority in the worlds in a little more detail.

**Comment by iTzAndrew33212** [comment]
So like if you protect an area within an area.
(A border) with flags set block break on, block place o, no pvp on priority 1 . (within A border have another area (B border) with flags set pvp on, block break off, block place off priority 2

Within area A you cant mine, place or pvp but area B within area A youd be able to mine, place blocks.....

**Comment by TrFolwe** [comment]
Thank you for your opinion, I think it complicates it for users, but I'll think about it, have a nice day...

Dear TrFolwe
Discord: trfolwe
