### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by UnknownNull** [TrFolwe/WorldGuardian#2]
2023-07-04 [21:32:41.041] [Server thread/CRITICAL]: TypeError: "TrFolwe\WorldGuardian\manager\WorldManager::getAreaPermission(): Argument #1 ($areaName) must be of type string, null given, called in C:\Users\Administrator\Documents\MV - RL\2.survival - pm5\plugins\WorldGuardian-main\src\TrFolwe\WorldGuardian\listener\WGuardListener.php on line 192" (EXCEPTION) in "plugins/WorldGuardian-main/src/TrFolwe/WorldGuardian/manager/WorldManager" at line 131
--- Stack trace ---
  #0 plugins/WorldGuardian-main/src/TrFolwe/WorldGuardian/listener/WGuardListener(192): TrFolwe\WorldGuardian\manager\WorldManager::getAreaPermission(null)
  #1 pmsrc/src/event/RegisteredListener(61): TrFolwe\WorldGuardian\listener\WGuardListener->onEntityByDamage(object pocketmine\event\entity\EntityDamageByEntityEvent#99609)
  #2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent#99609)
  #3 pmsrc/src/entity/Entity(528): pocketmine\event\Event->call()
  #4 pmsrc/src/entity/Living(539): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#99609)
  #5 pmsrc/src/player/Player(2451): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#99609)
  #6 pmsrc/src/player/Player(1865): pocketmine\player\Player->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#99609)
  #7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(559): pocketmine\player\Player->attackEntity(object pocketmine\player\Player#38689)
  #8 pmsrc/src/network/mcpe/handler/InGamePacketHandler(346): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemOnEntityTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemOnEntityTransactionData#345106)
  #9 pmsrc/vendor/nethergamesmc/bedrock-protocol/src/InventoryTransactionPacket(94): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#312583)
  #10 pmsrc/src/network/mcpe/NetworkSession(530): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#250145)
  #11 pmsrc/src/network/mcpe/NetworkSession(473): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#312583, string[32] ........9..Cr=.Bx..C............)
  #12 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[116] c.aj`d..J....S....:.P...(.....\..VbU..X.Z... ... ...`.t.s.m.S..mg.$`>.1.y....\..)
  #13 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 8, string[117] .c.aj`d..J....S....:.P...(.....\..VbU..X.Z... ... ...`.t.s.m.S..mg.$`>.1.y....\.)
  #14 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#42417)
  #15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #16 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #18 pmsrc/src/Server(1687): pocketmine\snooze\SleeperHandler->sleepUntil(float 1688506361.0683)
  #19 pmsrc/src/Server(1075): pocketmine\Server->tickProcessor()
  #20 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[58] C:\Users\Administrator\Documents\MV - RL\2.survival - pm5\, string[66] C:\Users\Administrator\Documents\MV - RL\2.survival - pm5\plugins\)
  #21 pmsrc/src/PocketMine(357): pocketmine\server()
  #22 pmsrc(11): require(string[102] phar://C:/Users/Administrator/Documents/MV - RL/2.survival - pm5/PocketMine-MP.p)

**Comment by TrFolwe** [comment]
First of all, is the person out of the area you've hit hello?

**Comment by UnknownNull** [comment]
Hi, I don't know.  I used this plugin on production server

**Comment by TrFolwe** [comment]
FIXED, crash fixed, thank you very much for choosing my plugin and good evening.

Dear TrFolwe
contact Discord: trfolwe
