### ISSUE TITLE
Damage by bow

### ISSUE THREAD

**Issue by UnknownNull** [TrFolwe/WorldGuardian#3]
In places where pvp is closed, players can damage others using bow or enderperl.  Make sure that after you add this feature, players outside the safe cannot damage the people inside using anything.

**Comment by TrFolwe** [comment]
Sure, thanks

**Comment by UnknownNull** [comment]
It is free to place blocks in the specified areas with accuracy if it is closed in the settings

**Comment by UnknownNull** [comment]
I fixed it for myself by editing the plugin
